import { Product, Client, StockEntry, Payable, PaymentStatus, ClientType } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Hamburguer Supremo',
    category: 'Lanches',
    fiscalGroup: 'Revenda - Receita Normal',
    price: 29.9,
    cost: 12.0,
    stock: 45,
    minStock: 10,
    unit: 'UN',
    status: 'Ativo',
    ncm: '2106.90.90',
    ncmDescription: 'Preparacoes alimenticias',
    ean: '789123456001',
    origem: '0',
    taxCode: '102',
    cest: '',
    taxNeedsReview: false,
  },
  {
    id: '2',
    name: 'Coca-Cola 350ml',
    category: 'Bebidas',
    fiscalGroup: 'Revenda - Monofasico + ST',
    price: 6.0,
    cost: 2.5,
    stock: 120,
    minStock: 24,
    unit: 'UN',
    status: 'Ativo',
    ncm: '2202.10.00',
    ncmDescription: 'Aguas, inclui aguas minerais e gaseificadas',
    ean: '789123456002',
    origem: '0',
    taxCode: '500',
    cest: '',
    taxNeedsReview: false,
  },
  {
    id: '3',
    name: 'Batata Frita G',
    category: 'Porcoes',
    fiscalGroup: 'Revenda - ST',
    price: 22.0,
    cost: 8.0,
    stock: 5,
    minStock: 20,
    unit: 'UN',
    status: 'Ativo',
    ncm: '2004.10.00',
    ncmDescription: 'Produtos horticolas preparados',
    origem: '0',
    taxCode: '201',
    cest: '',
    taxNeedsReview: false,
  },
  {
    id: '4',
    name: 'Suco de Laranja',
    category: 'Bebidas',
    fiscalGroup: 'Revenda - Receita Normal',
    price: 9.0,
    cost: 3.0,
    stock: 30,
    minStock: 10,
    unit: 'UN',
    status: 'Inativo',
    origem: '0',
    taxCode: '102',
    taxNeedsReview: false,
  },
];

export const MOCK_CLIENTS: Client[] = [
  {
    id: '1',
    name: 'Joao Silva',
    type: ClientType.PF,
    document: '123.456.789-00',
    phone: '(11) 99999-1234',
    creditLimit: 500,
    status: 'Ativo',
    balance: 156.5,
    ieIndicator: '3',
    cep: '30130-110',
    street: 'Av. Afonso Pena',
    number: '1000',
    district: 'Centro',
    city: 'Belo Horizonte',
    uf: 'MG',
    cityCode: '3106200',
    nfeEligible: true,
  },
  {
    id: '2',
    name: 'Maria Souza',
    type: ClientType.PF,
    document: '234.567.890-11',
    phone: '(11) 98888-5678',
    creditLimit: 200,
    status: 'Ativo',
    balance: 0,
    ieIndicator: '3',
    cep: '29010-000',
    street: 'Rua Sete',
    number: '220',
    district: 'Centro',
    city: 'Vitoria',
    uf: 'ES',
    cityCode: '3205309',
    nfeEligible: true,
  },
  {
    id: '3',
    name: 'Tech Solutions Ltda',
    type: ClientType.PJ,
    document: '12.345.678/0001-90',
    phone: '(11) 3333-4444',
    creditLimit: 2000,
    status: 'Ativo',
    balance: 450.0,
    ieIndicator: '1',
    ie: '',
    cep: '',
    street: '',
    number: '',
    district: '',
    city: '',
    uf: 'MG',
    cityCode: '',
    nfeEligible: false,
  },
];

export const MOCK_STOCK_ENTRIES: StockEntry[] = [
  { id: '101', date: '2023-10-25', supplier: 'Atacadao de Bebidas', itemsCount: 3, total: 1250.0, status: 'Aprovada' },
  { id: '102', date: '2023-10-26', supplier: 'Frigorifico Boi Gordo', itemsCount: 1, total: 890.0, status: 'Pendente' },
];

export const MOCK_PAYABLES: Payable[] = [
  { id: '201', dueDate: '2023-11-05', supplier: 'Energia Eletrica S.A.', description: 'Conta de Luz Out/23', value: 450.0, status: 'Aberto', type: 'Fixo' },
  { id: '202', dueDate: '2023-11-10', supplier: 'Atacadao de Bebidas', description: 'NFe 44512 - Reposicao', value: 1250.0, status: 'Aberto', type: 'Boleto' },
  { id: '203', dueDate: '2023-10-30', supplier: 'Imobiliaria Central', description: 'Aluguel Out/23', value: 3500.0, status: 'Pago', type: 'Fixo' },
];

export const MOCK_STATEMENT = [
  { id: 'v101', date: '2023-10-20 19:30', items: ['1x Hamburguer Supremo', '1x Coca 350ml'], value: 35.9, status: PaymentStatus.NAO_PAGO },
  { id: 'v102', date: '2023-10-22 12:15', items: ['2x Prato Feito', '2x Suco'], value: 68.0, status: PaymentStatus.NAO_PAGO },
  { id: 'v099', date: '2023-10-15 20:00', items: ['1x Pizza Grande'], value: 52.6, status: PaymentStatus.PAGO },
];
